/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_runtime_rpc_pekko_CxlConnector */

#ifndef _Included_org_apache_flink_runtime_rpc_pekko_CxlConnector
#define _Included_org_apache_flink_runtime_rpc_pekko_CxlConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_create
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    get_position
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_get_1position
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    write_buf
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_write_1buf
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    read_size
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_read_1size
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_apache_flink_runtime_rpc_pekko_CxlConnector
 * Method:    read_buf
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_rpc_pekko_CxlConnector_read_1buf
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
